on:
  push: # push 이벤트 감지
    pull_request: # 브랜치 이벤트 중
      - 'main*' # master로 시작하는 브랜치에 대한 pull request 이벤트 감지

jobs:
  build: # build 작업
    runs-on: ubuntu-latest # 우분투 환경에서 실행
    steps: # 실행할 작업들

      - name: Checkout code # 코드 체크아웃 액션 실행
        uses: actions/checkout@v2

      - name: Run custom command # 사용자 정의 명령어 실행
        if: startsWith(github.ref, 'refs/heads/master') # github.ref가 'refs/heads/master'로 시작하는지 확인

        run: | # 실행할 명령어들
          echo Add other actions to build, # 빌드할 다른 작업 추가
          echo test, and deploy your project. # 프로젝트 테스트 및 배포
